### ISSUE TITLE
Ideas for figures for the paper

### ISSUE THREAD

**Issue by mdscheuerell** [mdscheuerell/mar_sims#7]
Here are my thoughts for figures in the main text of the paper.

[Figure 1](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Estimated%20obs%20error.pdf). Effects of prior information on estimates of the observation SD.

[Figure 2](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Estimated%20process%20error.pdf). Effects of prior information on estimates of the process SD.

[Figure 3](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Obs%20v%20process%20error.pdf). Effects of prior information on tradeoffs between estimates of observation and process errors.

[Figure 4](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Estimated_b_elements_bCV_ungrouped.pdf). Effect of prior information on estimates of intra- and inter-species interaction strengths.

(I'm imagining a modified version of the current figure with 2 examples: one with obs > proc and the other with obs < proc; the former showing the (expectedly) worse pathology. We could include the other examples in the supplement.)

**Comment by mdscheuerell** [comment]
Based on phone call on 06 Mar 2020, we discussed using the following levels of obs and process SD's:

* case 1: obs = 0.2; proc = 0.4

* case 2: obs = 0.4; proc = 0.2

**Comment by ericward-noaa** [comment]
I like the order of plots, and did a little cleaning of # 1-3 while sims for # 4 are running. New version:

[Figure 1](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Estimated%20obs%20error.pdf)
[Figure 2](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Estimated%20process%20error.pdf)
[Figure 3](https://github.com/mdscheuerell/mar_sims/blob/master/plots/Obs%20v%20process%20error.pdf)

**Comment by sl-katz63** [comment]
https://twitter.com/farrwill/status/1155803989834944512
